### ISSUE TITLE
"Query is empty" error is displayed after attempt to open custom filter that was saved in "Tests Query Editor" 

### ISSUE THREAD

**Issue by dmytro-lgtm** [testomatio/app#1174]
**Describe the bug**
Can't open custom filter that was saved in "Tests Query Editor"

**To Reproduce**
1. Click the "Query Language Editor" button
2. Enter `label == 'Desktop'` query and click the "Save" button
3. Enter the query name and click the "Save" button
4. Click saved filter link in the "Saved Queries" section

**Actual result:** "Error" pop-up with text "Query is empty" appears. Next console error is thrown:
```
Uncaught (in promise) Error: Illegal argument
    at p (editor.main.js:sourcemap:10:960)
    at Wt.setValue (editor.main.js:sourcemap:640:461)
    at e.StandaloneEditor.setValue (editor.main.js:sourcemap:655:97)
    at frame.js:sourcemap:1362:18
    at m._invokeFactory (loader.js:8:1491)
    at m.complete (loader.js:8:1706)
    at c._onModuleComplete (loader.js:9:1051)
    at c._resolve (loader.js:9:510)
    at c.defineModule (loader.js:8:5548)
    at r (loader.js:9:2178)
```

**Expected behavior**
The saved filter is shown

**Screenshots**
<img width="1348" alt="Screenshot 2024-11-29 at 17 25 19" src="https://github.com/user-attachments/assets/d2eff746-845f-4003-9ee1-0ec35dc12c70">

**Desktop (please complete the following information):**
 - OS: MacOS 15.1.1
 - Browser Chrome
 - Browser Version 131.0.6778.86
 - Application: production

**Additional context**

**Comment by TetianaKhomenko** [comment]
Hi @dmytro-lgtm! Thanks for reporting the issue. The fix is live now.
