### ISSUE TITLE
can't execute codecept.js tests

### ISSUE THREAD

**Issue by poliarush** [testomatio/app#142]
on beta 

![image](https://user-images.githubusercontent.com/325722/84057101-7aa58a80-a9b7-11ea-8f15-5b678f856150.png)

**Comment by poliarush** [comment]
jest is not working also
```
 ~/D/t/t/d/examples    jest  env TESTOMATIO_URL=https://beta.testomat.io/api/load TESTOMATIO=qd0c48d6aezm npx jest
[Testomatio] Error creating run, skipping... Error: Request failed with status code 404
    at createError (/Users/poliarush/Documents/temp/testomat/demo1/examples/jest/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/Users/poliarush/Documents/temp/testomat/demo1/examples/jest/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/Users/poliarush/Documents/temp/testomat/demo1/examples/jest/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  config: {
    url: 'https://beta.testomat.io/api/load/api/reporter',
    method: 'post',
    data: '{"api_key":"qd0c48d6aezm"}',
    headers: {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json;charset=utf-8',
      'User-Agent': 'axios/0.19.2',
      'Content-Length': 26
    },
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    adapter: [Function: httpAdapter],
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    validateStatus: [Function: validateStatus]
  },
  request: ClientRequest {
    _events: [Object: null prototype] {
      socket: [Function],
      abort: [Function],
      aborted: [Function],
      error: [Function],
      timeout: [Function],
      prefinish: [Function: requestOnPrefinish]
    },
    _eventsCount: 6,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'beta.testomat.io',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'beta.testomat.io',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 235,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    connection: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      _SNICallback: null,
      servername: 'beta.testomat.io',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 10,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'beta.testomat.io',
      _readableState: [ReadableState],
      readable: true,
      _maxListeners: undefined,
      _writableState: [WritableState],
      writable: false,
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: [TLSWrap],
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular],
      [Symbol(res)]: [TLSWrap],
      [Symbol(asyncId)]: 235,
      [Symbol(kHandle)]: [TLSWrap],
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /api/load/api/reporter HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json;charset=utf-8\r\n' +
      'User-Agent: axios/0.19.2\r\n' +
      'Content-Length: 26\r\n' +
      'Host: beta.testomat.io\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    insecureHTTPParser: undefined,
    path: '/api/load/api/reporter',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      readable: false,
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      socket: [TLSSocket],
      connection: [TLSSocket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      headers: [Object],
      rawHeaders: [Array],
      trailers: {},
      rawTrailers: [],
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 404,
      statusMessage: 'Not Found',
      client: [TLSSocket],
      _consuming: true,
      _dumped: false,
      req: [Circular],
      responseUrl: 'https://beta.testomat.io/api/load/api/reporter',
      redirects: [],
      [Symbol(kCapture)]: false
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    _redirectable: Writable {
      _writableState: [WritableState],
      writable: true,
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _options: [Object],
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 26,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function],
      _currentRequest: [Circular],
      _currentUrl: 'https://beta.testomat.io/api/load/api/reporter',
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  response: {
    status: 404,
    statusText: 'Not Found',
    headers: {
      'content-type': 'text/html; charset=UTF-8',
      'content-length': '1722',
      connection: 'close',
      status: '404 Not Found',
      'x-request-id': 'b63ddf74-b168-40b6-90df-ddf43aa09680',
      'x-runtime': '0.002102',
      date: 'Mon, 08 Jun 2020 16:42:04 GMT',
      'x-powered-by': 'Phusion Passenger 6.0.4',
      server: 'nginx/1.14.0 + Phusion Passenger 6.0.4'
    },
    config: {
      url: 'https://beta.testomat.io/api/load/api/reporter',
      method: 'post',
      data: '{"api_key":"qd0c48d6aezm"}',
      headers: [Object],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 0,
      adapter: [Function: httpAdapter],
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      validateStatus: [Function: validateStatus]
    },
    request: ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: null,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      connection: [TLSSocket],
      _header: 'POST /api/load/api/reporter HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json;charset=utf-8\r\n' +
        'User-Agent: axios/0.19.2\r\n' +
        'Content-Length: 26\r\n' +
        'Host: beta.testomat.io\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      insecureHTTPParser: undefined,
      path: '/api/load/api/reporter',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    data: '<!DOCTYPE html>\n' +
      '<html>\n' +
      '<head>\n' +
      "  <title>The page you were looking for doesn't exist (404)</title>\n" +
      '  <meta name="viewport" content="width=device-width,initial-scale=1">\n' +
      '  <style>\n' +
      '  .rails-default-error-page {\n' +
      '    background-color: #EFEFEF;\n' +
      '    color: #2E2F30;\n' +
      '    text-align: center;\n' +
      '    font-family: arial, sans-serif;\n' +
      '    margin: 0;\n' +
      '  }\n' +
      '\n' +
      '  .rails-default-error-page div.dialog {\n' +
      '    width: 95%;\n' +
      '    max-width: 33em;\n' +
      '    margin: 4em auto 0;\n' +
      '  }\n' +
      '\n' +
      '  .rails-default-error-page div.dialog > div {\n' +
      '    border: 1px solid #CCC;\n' +
      '    border-right-color: #999;\n' +
      '    border-left-color: #999;\n' +
      '    border-bottom-color: #BBB;\n' +
      '    border-top: #B00100 solid 4px;\n' +
      '    border-top-left-radius: 9px;\n' +
      '    border-top-right-radius: 9px;\n' +
      '    background-color: white;\n' +
      '    padding: 7px 12% 0;\n' +
      '    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);\n' +
      '  }\n' +
      '\n' +
      '  .rails-default-error-page h1 {\n' +
      '    font-size: 100%;\n' +
      '    color: #730E15;\n' +
      '    line-height: 1.5em;\n' +
      '  }\n' +
      '\n' +
      '  .rails-default-error-page div.dialog > p {\n' +
      '    margin: 0 0 1em;\n' +
      '    padding: 1em;\n' +
      '    background-color: #F7F7F7;\n' +
      '    border: 1px solid #CCC;\n' +
      '    border-right-color: #999;\n' +
      '    border-left-color: #999;\n' +
      '    border-bottom-color: #999;\n' +
      '    border-bottom-left-radius: 4px;\n' +
      '    border-bottom-right-radius: 4px;\n' +
      '    border-top-color: #DADADA;\n' +
      '    color: #666;\n' +
      '    box-shadow: 0 3px 8px rgba(50, 50, 50, 0.17);\n' +
      '  }\n' +
      '  </style>\n' +
      '</head>\n' +
      '\n' +
      '<body class="rails-default-error-page">\n' +
      '  <!-- This file lives in public/404.html -->\n' +
      '  <div class="dialog">\n' +
      '    <div>\n' +
      "      <h1>The page you were looking for doesn't exist.</h1>\n" +
      '      <p>You may have mistyped the address or the page may have moved.</p>\n' +
      '    </div>\n' +
      '    <p>If you are the application owner check the logs for more information.</p>\n' +
      '  </div>\n' +
      '</body>\n' +
      '</html>\n'
  },
  isAxiosError: true,
  toJSON: [Function]
}
 PASS  Algorithms/container-with-most-water/containerWithMostWater.test.js
 PASS  Algorithms/negative-index/negativeIndex.test.js
 PASS  Algorithms/least-common-multiple/leastCommonMultiple.test.js
 PASS  Algorithms/goat-latin/goatLatin.test.js
 PASS  DataStructure/binary-search-tree/binarySearchTree.test.js
 PASS  DataStructure/heap/heap.test.js
 PASS  Algorithms/animal-sort/animalSort.test.js
 PASS  DataStructure/sort/sort.test.js
 PASS  Algorithms/largest-substring/lengthOfSubstring.test.js
 PASS  Algorithms/find-all-duplicates/findDuplicate.test.js
 PASS  DataStructure/singly-linked-list/singlyLinkedList.test.js
 PASS  Algorithms/jewels-and-stones/jewelAndStone.test.js
 PASS  Algorithms/two-sum/two-sum.test.js
 PASS  Algorithms/stone-game/stoneGame.test.js
 PASS  Algorithms/remove-duplicate-sorted-array/removeDuplicate.test.js
 PASS  Algorithms/exce-column-title/excelCount.test.js
 PASS  Algorithms/find-duplicate/findDuplicate.test.js
 PASS  Algorithms/two-sum-2/twoSum.test.js
 PASS  Algorithms/group-people/groupPeople.test.js
 PASS  Algorithms/longest-palindrome/longestPalindrom.test.js
 PASS  Algorithms/fizz-buzz/fizzBuzz.test.js
 PASS  Algorithms/robot-return-to-origin/robot.test.js
 PASS  Algorithms/can-place-flowers/canPlaceFlowers.test.js
 PASS  Algorithms/reverse-integer/reverseInteger.test.js
 PASS  Algorithms/flight-booking/flightBooking.test.js
 PASS  Algorithms/sum-of-perfect-square/sumOfPerfectSquare.test.js
 PASS  sample/sample.test.js
 PASS  Algorithms/largest-number/largestNumber.test.js
 PASS  Algorithms/min-path-sum/minPathSum.test.js
 PASS  Algorithms/remove-element/removeElement.test.js
 PASS  Algorithms/threesum/threeSum.test.js

Test Suites: 31 passed, 31 total
Tests:       56 passed, 56 total
Snapshots:   0 total
Time:        3.037s, estimated 4s
Ran all test suites.
```

**Comment by poliarush** [comment]
endpoint will be changed for check-tests and reporter

**Comment by poliarush** [comment]
need to be tested
