### ISSUE TITLE
Error processing test.after event - Reporter CodeceptJS

### ISSUE THREAD

**Issue by AngelM-GL** [testomatio/app#562]
**Describe the bug**
The testomat codecept reporter throws an error when it comes to send the run report to testomat of a retried test, due to an undefined `test.steps` property in @testomatio/reporter/lib/adapter/codecept.js line 115, preventing the run report from being saved.

```
Error processing test.after event:
TypeError: Cannot read property 'length' of undefined
    at EventEmitter.<anonymous> (/Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/@testomatio/reporter/lib/adapter/codecept.js:115:40)
    at EventEmitter.emit (events.js:388:22)
    at EventEmitter.emit (domain.js:470:12)
    at Object.emit (/Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/codeceptjs/lib/event.js:145:28)
    at /Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/codeceptjs/lib/scenario.js:181:11
    at injectHook (/Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/codeceptjs/lib/scenario.js:9:5)
    at Object.module.exports.teardown (/Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/codeceptjs/lib/scenario.js:179:10)
    at Context.<anonymous> (/Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/codeceptjs/lib/interfaces/gherkin.js:30:54)
    at callFn (/Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/mocha/lib/runnable.js:358:21)
    at Hook.Runnable.run (/Users/angelmoraabalos/Recursos/Repos/sqa-at/node_modules/mocha/lib/runnable.js:346:5)
```

The following code checks if an error stack and the steps objects have data, but it fails at accesing `test.steps.length` as `test.steps` is undefined in a retry run.

```
if (err && err.stack && test.steps.length) {
      err.stack = test.steps[test.steps.length - 1].line();
}
```
It can be solved by adding an extra check to the line, checking if test.steps is undefined first.

```
if (err && err.stack && test.steps && test.steps.length) {
     err.stack = test.steps[test.steps.length - 1].line();
}
```

**To Reproduce**
1. Configure a rerun in CodeceptJS to execute if the test fails
2. Execute a run with a failing test
3. See the error stack
4. The run report of that test is not saved

**Expected behavior**
No error is thrown and the run report is successfully saved.

**Desktop (please complete the following information):**
 - OS: MacOS Monterey (12.0.1)
 - Browser: Chrome
 - Browser Version: 95.0.4638.69

**Additional context**
Using `  "@testomatio/reporter": "^0.3.15"`,     `"codeceptjs": "^3.1.3"` and `"playwright": "^1.15.2"`

**Comment by DavertMik** [comment]
Thanks, should be fixed in 0.3.16 
Please reopen if not
