### ISSUE TITLE
Cannot delete test run

### ISSUE THREAD

**Issue by TheZZ13** [testomatio/app#723]
**Describe the bug**
I cannot delete a test run that I have created. When I hit the three dot menu nothing happens. `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'file')`
   
**To Reproduce**
1. Navigate to https://app.testomat.io/projects/caesars-left-hand-tv/runs
2. Open the browser console.
3. Click on "QE-251 Caesars Left Hand TV regression..."
4. Wait for the page to load: https://app.testomat.io/projects/caesars-left-hand-tv/runs/313ce692
5. Scroll down to '....'
6. Select the three dot menu in the upper right corner.
7. View the page.
Actual Result: Nothing happens.

**Expected behavior**
The three dot menu should expand. 

**Screenshots**
Video here: https://drive.google.com/file/d/1ELcS4voamwCYYd1H51xNFowM8yyc-_5j/view?usp=sharing

**Desktop (please complete the following information):**
 - OS: Mac 13.3.1
 - Browser: Chrome
 - Browser Version: 113.0.5672.126
 - Application: Production

**Additional context**
Here's the data from the web console: 
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'file')
    at i.value (frontend.js:1:1412840)
    at frontend.js:1:1413614
    at Array.sort (<anonymous>)
    at i.get (frontend.js:1:1413585)
    at Me (vendor.js:13:113026)
    at vendor.js:13:350013
    at vendor.js:13:349670
    at e.track (vendor.js:13:440628)
    at m (vendor.js:13:349643)
    at vendor.js:13:349970
value @ frontend.js:1
(anonymous) @ frontend.js:1
get @ frontend.js:1
Me @ vendor.js:13
(anonymous) @ vendor.js:13
(anonymous) @ vendor.js:13
e.track @ vendor.js:13
m @ vendor.js:13
(anonymous) @ vendor.js:13
(anonymous) @ vendor.js:13
e.track @ vendor.js:13
m @ vendor.js:13
(anonymous) @ vendor.js:13
(anonymous) @ vendor.js:13
e.track @ vendor.js:13
m @ vendor.js:13
(anonymous) @ vendor.js:13
t.evaluate @ vendor.js:13
t.evaluateSyscall @ vendor.js:13
t.evaluateInner @ vendor.js:13
t.evaluateOuter @ vendor.js:13
i.next @ vendor.js:13
i._execute @ vendor.js:13
i.execute @ vendor.js:13
n.handleException @ vendor.js:13
t.handleException @ vendor.js:13
n.throw @ vendor.js:13
e.evaluate @ vendor.js:13
n._execute @ vendor.js:13
n.execute @ vendor.js:13
t.rerender @ vendor.js:13
c.render @ vendor.js:13
(anonymous) @ vendor.js:13
Rt @ vendor.js:13
i._renderRoots @ vendor.js:13
i._renderRootsTransaction @ vendor.js:13
i._revalidate @ vendor.js:13
t.invoke @ vendor.js:13
t.flush @ vendor.js:13
t.flush @ vendor.js:13
r._end @ vendor.js:13
_boundAutorunEnd @ vendor.js:13
Promise.then (async)
n @ vendor.js:13
flush @ vendor.js:13
r._scheduleAutorun @ vendor.js:13
r._end @ vendor.js:13
_boundAutorunEnd @ vendor.js:13
Promise.then (async)
n @ vendor.js:13
flush @ vendor.js:13
r._scheduleAutorun @ vendor.js:13
r._end @ vendor.js:13
_boundAutorunEnd @ vendor.js:13
Promise.then (async)
n @ vendor.js:13
flush @ vendor.js:13
r._scheduleAutorun @ vendor.js:13
r._end @ vendor.js:13
_boundAutorunEnd @ vendor.js:13
Promise.then (async)
n @ vendor.js:13
flush @ vendor.js:13
r._scheduleAutorun @ vendor.js:13
r._end @ vendor.js:13
_boundAutorunEnd @ vendor.js:13
Promise.then (async)
n @ vendor.js:13
flush @ vendor.js:13
r._scheduleAutorun @ vendor.js:13
r._ensureInstance @ vendor.js:13
r.schedule @ vendor.js:13
(anonymous) @ vendor.js:13
C @ vendor.js:13
p @ vendor.js:13
(anonymous) @ vendor.js:13
e.onload @ vendor.js:39
load (async)
(anonymous) @ vendor.js:39
(anonymous) @ vendor.js:13
e @ vendor.js:13
m @ vendor.js:39
text @ vendor.js:39
e.determineBodyPromise @ vendor.js:60
(anonymous) @ vendor.js:60
b @ vendor.js:13
H @ vendor.js:13
t.invoke @ vendor.js:13
t.flush @ vendor.js:13
t.flush @ vendor.js:13
r._end @ vendor.js:13
_boundAutorunEnd @ vendor.js:13
Promise.then (async)
n @ vendor.js:13
flush @ vendor.js:13
r._scheduleAutorun @ vendor.js:13
r._ensureInstance @ vendor.js:13
r.schedule @ vendor.js:13
(anonymous) @ vendor.js:13
C @ vendor.js:13
f @ vendor.js:13
p @ vendor.js:13
(anonymous) @ vendor.js:13
(anonymous) @ vendor.js:39
setTimeout (async)
c.onload @ vendor.js:39
load (async)
(anonymous) @ vendor.js:39
(anonymous) @ vendor.js:13
e @ vendor.js:13
_ @ vendor.js:39
p._fetchRequest @ vendor.js:60
p.ajax @ vendor.js:60
p.findRecord @ vendor.js:60
value @ frontend.js:1
(anonymous) @ vendor.js:60
b @ vendor.js:13
(anonymous) @ vendor.js:13
t.invoke @ vendor.js:13
t.flush @ vendor.js:13
t.flush @ vendor.js:13
r._end @ vendor.js:13
_boundAutorunEnd @ vendor.js:13
Promise.then (async)
n @ vendor.js:13
flush @ vendor.js:13
r._scheduleAutorun @ vendor.js:13
r._ensureInstance @ vendor.js:13
r.schedule @ vendor.js:13
(anonymous) @ vendor.js:13
y @ vendor.js:13
t.resolve @ vendor.js:13
e @ vendor.js:13
r.getTransitionByIntent @ vendor.js:13
r.transitionByIntent @ vendor.js:13
r.doTransition @ vendor.js:13
r.transitionTo @ vendor.js:13
l._doTransition @ vendor.js:13
i.transitionTo @ vendor.js:13
(anonymous) @ vendor.js:13
a @ vendor.js:13
i.click @ vendor.js:13
```

**Comment by TetianaKhomenko** [comment]
The issue was re-tested and verified as fixed.
