### ISSUE TITLE
Error updating status, skipping... {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500

### ISSUE THREAD

**Issue by leagaleano-codere** [testomatio/app#917]
**Describe the bug**
Error updating status, skipping... {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500

**To Reproduce**
CI=true TESTOMATIO_TITLE="MSO enable artefacts" TESTOMATIO_RUNGROUP_TITLE="Testomatio Report Issue" TESTOMATIO_CREATE=1 TESTOMATIO=6y84ad5143zj TESTOMATIO_URL= TESTOMATIO_RUN= TESTOMATIO_ENV="iphone" GREP="@qa,@mso" npx playwright test --project=chrome --grep "@mso.*@qa"

**Expected behavior**
PlayWright executes the test and the results are handled by Testomatio and artifacts uploaded

**Screenshots**
![image](https://github.com/testomatio/app/assets/157365869/2a2ee8bf-6aba-4778-84a5-bfe021152fd1)
[TESTOMATIO] Pipes: Testomatio Reporter
[TESTOMATIO] Testomatio Reporter v1.0.12
[TESTOMATIO] S3 were credentials obtained from Testomat.io...
[TESTOMATIO] 📊 Report created. Report ID: 6d468c95
[TESTOMATIO] 🎞️  Uploading 26 files...
{}
[TESTOMATIO] Failed uploading 'aeebe514-de6a-4f76-983e-3e7f19b6c45c/7ce072a5-10fe-4837-bee2-c260295ce3e4-trace.zip'. Please check S3 credentials {"S3_ENDPOINT":"
https://ams3.digitaloceanspaces.com","S3_REGION":"ams3","S3_BUCKET":"codere-artifacts","S3_ACCESS_KEY_ID":"***","S3_SECRET_ACCESS_KEY":"***"}
[TESTOMATIO] To disable artifact uploads set: TESTOMATIO_DISABLE_ARTIFACTS=1
[TESTOMATIO] To enable PRIVATE uploads set: TESTOMATIO_PRIVATE_ARTIFACTS=1
[TESTOMATIO] ---------------
{}
[TESTOMATIO] Failed uploading 'aeebe514-de6a-4f76-983e-3e7f19b6c45c/c2146ae5-c436-40f1-b3d9-3b0527336313-trace.zip'. Please check S3 credentials {"S3_ENDPOINT":"
https://ams3.digitaloceanspaces.com","S3_REGION":"ams3","S3_BUCKET":"codere-artifacts","S3_ACCESS_KEY_ID":"***","S3_SECRET_ACCESS_KEY":"***"}
[TESTOMATIO] To disable artifact uploads set: TESTOMATIO_DISABLE_ARTIFACTS=1
[TESTOMATIO] To enable PRIVATE uploads set: TESTOMATIO_PRIVATE_ARTIFACTS=1
[TESTOMATIO] ---------------
[TESTOMATIO] Error updating status, skipping... {"message":"Request failed with status code 500","name":"Error","stack":"Error: Request failed with status code 500\n    at createError (/Users/leandro/cod-repos/codere_e2e/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/Users/leandro/cod-repos/codere_e2e/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/Users/leandro/cod-repos/codere_e2e/node_modules/axios/lib/adapters/http.js:312:11)\n    at IncomingMessage.emit (node:events:524:35)\n    at endReadableNT (node:internal/streams/readable:1378:12)\n    at processTicksAndRejections (node:internal/process/task_queues:82:21)","config":{"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false},"transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json","User-Agent":"axios/0.25.0","Content-Length":48},"method":"put","url":"
[https://app.testomat.io/api/reporter/6d468c95","data":"{\"api_key\":\"6y84ad5143zj\",\"status_event\":\"fail\"}"},"status":500}](https://app.testomat.io/api/reporter/6d468c95%22,%22data%22:%22%7B/%22api_key/%22:/%226y84ad5143zj/%22,/%22status_event/%22:/%22fail/%22%7D%22%7D,%22status%22:500%7D)
[TESTOMATIO] 🗄️  Total 18 artifacts publicly uploaded to S3 bucket

**Desktop (please complete the following information):**
 - OS: [any *nix OS]
 - Application: [production] 

**Additional context**

**Comment by TetianaKhomenko** [comment]
The issue was fixed.
