### ISSUE TITLE
API error response when running PlayWright

### ISSUE THREAD

**Issue by leagaleano-codere** [testomatio/app#921]
**Describe the bug**
When running tests on Playwright with Testomatio, the tests are not completed and error is displayed.

**To Reproduce**
1. Run any test, and it fails with the following section:

2024-01-31T14:36:27.0277262Z                        ^^^^^^^^^^^ (400) payments - panama - deposits - crow casino - validate crown casino links are right @qa @mirror @prod @T3208e26c
2024-01-31T14:36:27.1633684Z [TESTOMATIO] Warning: undefined method `scheduled?' for nil:NilClass
2024-01-31T14:36:27.1634235Z 
2024-01-31T14:36:27.1634476Z     @run.launch if @run.scheduled?
2024-01-31T14:36:27.1635484Z                        ^^^^^^^^^^^ (400) payments - panama - withdrawls - crow casino - validate crown casino links are right @qa @mirror @prod
2024-01-31T14:36:27.2368647Z [TESTOMATIO] Error updating status, skipping... Error: Request failed with status code 404
2024-01-31T14:36:27.2369660Z     at createError (/azp/_work/1/s/node_modules/axios/lib/core/createError.js:16:15)
2024-01-31T14:36:27.2372412Z     at settle (/azp/_work/1/s/node_modules/axios/lib/core/settle.js:17:12)
2024-01-31T14:36:27.2372784Z     at IncomingMessage.handleStreamEnd (/azp/_work/1/s/node_modules/axios/lib/adapters/http.js:312:11)
2024-01-31T14:36:27.2374156Z     at IncomingMessage.emit (node:events:525:35)
2024-01-31T14:36:27.2374366Z     at endReadableNT (node:internal/streams/readable:1359:12)
2024-01-31T14:36:27.2374577Z     at processTicksAndRejections (node:internal/process/task_queues:82:21) {
2024-01-31T14:36:27.2374736Z   config: {
2024-01-31T14:36:27.2374988Z     transitional: {
2024-01-31T14:36:27.2379345Z       silentJSONParsing: true,
2024-01-31T14:36:27.2380419Z       forcedJSONParsing: true,
2024-01-31T14:36:27.2380852Z       clarifyTimeoutError: false
2024-01-31T14:36:27.2381237Z     },
2024-01-31T14:36:27.2381498Z     adapter: [Function: httpAdapter],
2024-01-31T14:36:27.2381822Z     transformRequest: [ [Function: transformRequest] ],
2024-01-31T14:36:27.2382025Z     transformResponse: [ [Function: transformResponse] ],
2024-01-31T14:36:27.2382181Z     timeout: 30000,
2024-01-31T14:36:27.2382639Z     xsrfCookieName: 'XSRF-TOKEN',
2024-01-31T14:36:27.2382872Z     xsrfHeaderName: 'X-XSRF-TOKEN',
2024-01-31T14:36:27.2388628Z     maxContentLength: -1,
2024-01-31T14:36:27.2388834Z     maxBodyLength: -1,
2024-01-31T14:36:27.2389013Z     validateStatus: [Function: validateStatus],
2024-01-31T14:36:27.2389170Z     headers: {
2024-01-31T14:36:27.2389823Z       Accept: 'application/json, text/plain, */*',
2024-01-31T14:36:27.2390075Z       'Content-Type': 'application/json',
2024-01-31T14:36:27.2390337Z       'User-Agent': 'axios/0.25.0',
2024-01-31T14:36:27.2390740Z       'Content-Length': 48
2024-01-31T14:36:27.2390859Z     },
2024-01-31T14:36:27.2391233Z     baseURL: 'https://app.testomat.io',
2024-01-31T14:36:27.2391429Z     method: 'put',
2024-01-31T14:36:27.2391635Z     url: '/api/reporter/9e03b9c0',
2024-01-31T14:36:27.2391915Z     data: '{"api_key":"6y84ad5143zj","status_event":"fail"}'
2024-01-31T14:36:27.2392072Z   },
2024-01-31T14:36:27.2392215Z   request: <ref *1> ClientRequest {
2024-01-31T14:36:27.2392367Z     _events: [Object: null prototype] {
2024-01-31T14:36:27.2392526Z       abort: [Function (anonymous)],
2024-01-31T14:36:27.2392694Z       aborted: [Function (anonymous)],
2024-01-31T14:36:27.2392847Z       connect: [Function (anonymous)],
2024-01-31T14:36:27.2393146Z       error: [Function (anonymous)],
2024-01-31T14:36:27.2437062Z       socket: [Function (anonymous)],
2024-01-31T14:36:27.2437385Z       timeout: [Function (anonymous)],
2024-01-31T14:36:27.2437912Z       finish: [Function: requestOnFinish]
2024-01-31T14:36:27.2438149Z     },
2024-01-31T14:36:27.2438381Z     _eventsCount: 7,
2024-01-31T14:36:27.2438608Z     _maxListeners: undefined,
2024-01-31T14:36:27.2438789Z     outputData: [],
2024-01-31T14:36:27.2438944Z     outputSize: 0,
2024-01-31T14:36:27.2439052Z     writable: true,
2024-01-31T14:36:27.2439178Z     destroyed: false,
2024-01-31T14:36:27.2439318Z     _last: true,
2024-01-31T14:36:27.2439431Z     chunkedEncoding: false,
2024-01-31T14:36:27.2439578Z     shouldKeepAlive: false,
2024-01-31T14:36:27.2439807Z     maxRequestsOnConnectionReached: false,
2024-01-31T14:36:27.2440042Z     _defaultKeepAlive: true,
2024-01-31T14:36:27.2440188Z     useChunkedEncodingByDefault: true,
2024-01-31T14:36:27.2440398Z     sendDate: false,
2024-01-31T14:36:27.2440687Z     _removedConnection: false,
2024-01-31T14:36:27.2440929Z     _removedContLen: false,
2024-01-31T14:36:27.2441159Z     _removedTE: false,
2024-01-31T14:36:27.2441405Z     strictContentLength: false,
2024-01-31T14:36:27.2441625Z     _contentLength: 48,
2024-01-31T14:36:27.2441862Z     _hasBody: true,
2024-01-31T14:36:27.2442043Z     _trailer: '',
2024-01-31T14:36:27.2442190Z     finished: true,
2024-01-31T14:36:27.2442301Z     _headerSent: true,
2024-01-31T14:36:27.2442411Z     _closed: false,
2024-01-31T14:36:27.2442535Z     socket: TLSSocket {
2024-01-31T14:36:27.2443111Z       _tlsOptions: [Object],
2024-01-31T14:36:27.2443340Z       _secureEstablished: true,
2024-01-31T14:36:27.2443471Z       _securePending: false,
2024-01-31T14:36:27.2443595Z       _newSessionPending: false,
2024-01-31T14:36:27.2444004Z       _controlReleased: true,
2024-01-31T14:36:27.2444214Z       secureConnecting: false,
2024-01-31T14:36:27.2444450Z       _SNICallback: null,
2024-01-31T14:36:27.2445027Z       servername: 'app.testomat.io',
2024-01-31T14:36:27.2445247Z       alpnProtocol: false,
2024-01-31T14:36:27.2445387Z       authorized: true,
2024-01-31T14:36:27.2445506Z       authorizationError: null,
2024-01-31T14:36:27.2445636Z       encrypted: true,
2024-01-31T14:36:27.2445757Z       _events: [Object: null prototype],
2024-01-31T14:36:27.2445881Z       _eventsCount: 10,
2024-01-31T14:36:27.2446006Z       connecting: false,
2024-01-31T14:36:27.2446118Z       _hadError: false,
2024-01-31T14:36:27.2446240Z       _parent: null,
2024-01-31T14:36:27.2446417Z       _host: 'app.testomat.io',
2024-01-31T14:36:27.2446554Z       _closeAfterHandlingError: false,
2024-01-31T14:36:27.2446704Z       _readableState: [ReadableState],
2024-01-31T14:36:27.2446833Z       _maxListeners: undefined,
2024-01-31T14:36:27.2446976Z       _writableState: [WritableState],
2024-01-31T14:36:27.2447107Z       allowHalfOpen: false,
2024-01-31T14:36:27.2447221Z       _sockname: null,
2024-01-31T14:36:27.2447378Z       _pendingData: null,
2024-01-31T14:36:27.2447496Z       _pendingEncoding: '',
2024-01-31T14:36:27.2447662Z       server: undefined,
2024-01-31T14:36:27.2447774Z       _server: null,
2024-01-31T14:36:27.2447880Z       ssl: [TLSWrap],
2024-01-31T14:36:27.2448027Z       _requestCert: true,
2024-01-31T14:36:27.2448148Z       _rejectUnauthorized: true,
2024-01-31T14:36:27.2448274Z       parser: null,
2024-01-31T14:36:27.2448390Z       _httpMessage: [Circular *1],
2024-01-31T14:36:27.2448508Z       timeout: 30000,
2024-01-31T14:36:27.2448638Z       [Symbol(res)]: [TLSWrap],
2024-01-31T14:36:27.2448760Z       [Symbol(verified)]: true,
2024-01-31T14:36:27.2448997Z       [Symbol(pendingSession)]: null,
2024-01-31T14:36:27.2449218Z       [Symbol(async_id_symbol)]: 18537,
2024-01-31T14:36:27.2449455Z       [Symbol(kHandle)]: [TLSWrap],
2024-01-31T14:36:27.2449778Z       [Symbol(lastWriteQueueSize)]: 0,
2024-01-31T14:36:27.2450033Z       [Symbol(timeout)]: Timeout {
2024-01-31T14:36:27.2450173Z         _idleTimeout: 30000,
2024-01-31T14:36:27.2450292Z         _idlePrev: [TimersList],
2024-01-31T14:36:27.2450415Z         _idleNext: [TimersList],
2024-01-31T14:36:27.2450635Z         _idleStart: 361874,
2024-01-31T14:36:27.2450836Z         _onTimeout: [Function: bound ],
2024-01-31T14:36:27.2451072Z         _timerArgs: undefined,
2024-01-31T14:36:27.2451270Z         _repeat: null,
2024-01-31T14:36:27.2451493Z         _destroyed: false,
2024-01-31T14:36:27.2451755Z         [Symbol(refed)]: false,
2024-01-31T14:36:27.2452014Z         [Symbol(kHasPrimitive)]: false,
2024-01-31T14:36:27.2452240Z         [Symbol(asyncId)]: 18545,
2024-01-31T14:36:27.2452372Z         [Symbol(triggerId)]: 18540
2024-01-31T14:36:27.2452477Z       },
2024-01-31T14:36:27.2452598Z       [Symbol(kBuffer)]: null,
2024-01-31T14:36:27.2452720Z       [Symbol(kBufferCb)]: null,
2024-01-31T14:36:27.2452862Z       [Symbol(kBufferGen)]: null,
2024-01-31T14:36:27.2453020Z       [Symbol(kCapture)]: false,
2024-01-31T14:36:27.2453230Z       [Symbol(kSetNoDelay)]: false,
2024-01-31T14:36:27.2453540Z       [Symbol(kSetKeepAlive)]: true,
2024-01-31T14:36:27.2453829Z       [Symbol(kSetKeepAliveInitialDelay)]: 60,
2024-01-31T14:36:27.2454122Z       [Symbol(kBytesRead)]: 0,
2024-01-31T14:36:27.2454312Z       [Symbol(kBytesWritten)]: 0,
2024-01-31T14:36:27.2456064Z       [Symbol(connect-options)]: [Object]
2024-01-31T14:36:27.2456286Z     },
2024-01-31T14:36:27.2456727Z     _header: 'PUT /api/reporter/9e03b9c0 HTTP/1.1\r\n' +
2024-01-31T14:36:27.2457149Z       'Accept: application/json, text/plain, */*\r\n' +
2024-01-31T14:36:27.2457550Z       'Content-Type: application/json\r\n' +
2024-01-31T14:36:27.2458253Z       'User-Agent: axios/0.25.0\r\n' +
2024-01-31T14:36:27.2458580Z       'Content-Length: 48\r\n' +
2024-01-31T14:36:27.2458922Z       'Host: app.testomat.io\r\n' +
2024-01-31T14:36:27.2459278Z       'Connection: close\r\n' +
2024-01-31T14:36:27.2459588Z       '\r\n',
2024-01-31T14:36:27.2459716Z     _keepAliveTimeout: 0,
2024-01-31T14:36:27.2459842Z     _onPendingData: [Function: nop],
2024-01-31T14:36:27.2460029Z     agent: Agent {
2024-01-31T14:36:27.2460249Z       _events: [Object: null prototype],
2024-01-31T14:36:27.2460487Z       _eventsCount: 2,
2024-01-31T14:36:27.2460751Z       _maxListeners: undefined,
2024-01-31T14:36:27.2460997Z       defaultPort: 443,
2024-01-31T14:36:27.2461280Z       protocol: 'https:',
2024-01-31T14:36:27.2461524Z       options: [Object: null prototype],
2024-01-31T14:36:27.2461727Z       requests: [Object: null prototype] {},
2024-01-31T14:36:27.2461946Z       sockets: [Object: null prototype],
2024-01-31T14:36:27.2462175Z       freeSockets: [Object: null prototype] {},
2024-01-31T14:36:27.2462314Z       keepAliveMsecs: 1000,
2024-01-31T14:36:27.2462445Z       keepAlive: false,
2024-01-31T14:36:27.2462561Z       maxSockets: Infinity,
2024-01-31T14:36:27.2462691Z       maxFreeSockets: 256,
2024-01-31T14:36:27.2462873Z       scheduling: 'lifo',
2024-01-31T14:36:27.2462995Z       maxTotalSockets: Infinity,
2024-01-31T14:36:27.2463129Z       totalSocketCount: 1,
2024-01-31T14:36:27.2463247Z       maxCachedSessions: 100,
2024-01-31T14:36:27.2463382Z       _sessionCache: [Object],
2024-01-31T14:36:27.2463504Z       [Symbol(kCapture)]: false
2024-01-31T14:36:27.2463607Z     },
2024-01-31T14:36:27.2463729Z     socketPath: undefined,
2024-01-31T14:36:27.2463887Z     method: 'PUT',
2024-01-31T14:36:27.2464018Z     maxHeaderSize: undefined,
2024-01-31T14:36:27.2464147Z     insecureHTTPParser: undefined,
2024-01-31T14:36:27.2464280Z     joinDuplicateHeaders: undefined,
2024-01-31T14:36:27.2464488Z     path: '/api/reporter/9e03b9c0',
2024-01-31T14:36:27.2464608Z     _ended: true,
2024-01-31T14:36:27.2464778Z     res: IncomingMessage {
2024-01-31T14:36:27.2464914Z       _readableState: [ReadableState],
2024-01-31T14:36:27.2465141Z       _events: [Object: null prototype],
2024-01-31T14:36:27.2465379Z       _eventsCount: 4,
2024-01-31T14:36:27.2465569Z       _maxListeners: undefined,
2024-01-31T14:36:27.2465746Z       socket: [TLSSocket],
2024-01-31T14:36:27.2465946Z       httpVersionMajor: 1,
2024-01-31T14:36:27.2466114Z       httpVersionMinor: 1,
2024-01-31T14:36:27.2466432Z       httpVersion: '1.1',
2024-01-31T14:36:27.2466650Z       complete: true,
2024-01-31T14:36:27.2466869Z       rawHeaders: [Array],
2024-01-31T14:36:27.2467102Z       rawTrailers: [],
2024-01-31T14:36:27.2467340Z       joinDuplicateHeaders: undefined,
2024-01-31T14:36:27.2467595Z       aborted: false,
2024-01-31T14:36:27.2467808Z       upgrade: false,
2024-01-31T14:36:27.2468015Z       url: '',
2024-01-31T14:36:27.2468229Z       method: null,
2024-01-31T14:36:27.2468439Z       statusCode: 404,
2024-01-31T14:36:27.2468802Z       statusMessage: 'Not Found',
2024-01-31T14:36:27.2468929Z       client: [TLSSocket],
2024-01-31T14:36:27.2469161Z       _consuming: false,
2024-01-31T14:36:27.2469272Z       _dumped: false,
2024-01-31T14:36:27.2469433Z       req: [Circular *1],
2024-01-31T14:36:27.2469674Z       responseUrl: 'https://app.testomat.io/api/reporter/9e03b9c0',
2024-01-31T14:36:27.2469832Z       redirects: [],
2024-01-31T14:36:27.2469947Z       [Symbol(kCapture)]: false,
2024-01-31T14:36:27.2470070Z       [Symbol(kHeaders)]: [Object],
2024-01-31T14:36:27.2470209Z       [Symbol(kHeadersCount)]: 30,
2024-01-31T14:36:27.2470334Z       [Symbol(kTrailers)]: null,
2024-01-31T14:36:27.2470472Z       [Symbol(kTrailersCount)]: 0
2024-01-31T14:36:27.2470576Z     },
2024-01-31T14:36:27.2470674Z     aborted: false,
2024-01-31T14:36:27.2470801Z     timeoutCb: null,
2024-01-31T14:36:27.2470918Z     upgradeOrConnect: false,
2024-01-31T14:36:27.2471044Z     parser: null,
2024-01-31T14:36:27.2471156Z     maxHeadersCount: null,
2024-01-31T14:36:27.2471440Z     reusedSocket: false,
2024-01-31T14:36:27.2471634Z     host: 'app.testomat.io',
2024-01-31T14:36:27.2471813Z     protocol: 'https:',
2024-01-31T14:36:27.2471935Z     _redirectable: Writable {
2024-01-31T14:36:27.2472157Z       _writableState: [WritableState],
2024-01-31T14:36:27.2472291Z       _events: [Object: null prototype],
2024-01-31T14:36:27.2472426Z       _eventsCount: 3,
2024-01-31T14:36:27.2472544Z       _maxListeners: undefined,
2024-01-31T14:36:27.2472662Z       _options: [Object],
2024-01-31T14:36:27.2472784Z       _ended: true,
2024-01-31T14:36:27.2472890Z       _ending: true,
2024-01-31T14:36:27.2473012Z       _redirectCount: 0,
2024-01-31T14:36:27.2473122Z       _redirects: [],
2024-01-31T14:36:27.2473236Z       _requestBodyLength: 48,
2024-01-31T14:36:27.2473369Z       _requestBodyBuffers: [],
2024-01-31T14:36:27.2473503Z       _onNativeResponse: [Function (anonymous)],
2024-01-31T14:36:27.2473655Z       _currentRequest: [Circular *1],
2024-01-31T14:36:27.2473900Z       _currentUrl: 'https://app.testomat.io/api/reporter/9e03b9c0',
2024-01-31T14:36:27.2474043Z       _timeout: null,
2024-01-31T14:36:27.2474173Z       [Symbol(kCapture)]: false
2024-01-31T14:36:27.2474276Z     },
2024-01-31T14:36:27.2474397Z     [Symbol(kCapture)]: false,
2024-01-31T14:36:27.2474521Z     [Symbol(kBytesWritten)]: 0,
2024-01-31T14:36:27.2474646Z     [Symbol(kNeedDrain)]: false,
2024-01-31T14:36:27.2474777Z     [Symbol(corked)]: 0,
2024-01-31T14:36:27.2474910Z     [Symbol(kOutHeaders)]: [Object: null prototype] {
2024-01-31T14:36:27.2475052Z       accept: [Array],
2024-01-31T14:36:27.2475221Z       'content-type': [Array],
2024-01-31T14:36:27.2475393Z       'user-agent': [Array],
2024-01-31T14:36:27.2475584Z       'content-length': [Array],
2024-01-31T14:36:27.2475699Z       host: [Array]
2024-01-31T14:36:27.2475807Z     },
2024-01-31T14:36:27.2475912Z     [Symbol(errored)]: null,
2024-01-31T14:36:27.2476038Z     [Symbol(kUniqueHeaders)]: null
2024-01-31T14:36:27.2476158Z   },
2024-01-31T14:36:27.2476653Z   response: {
2024-01-31T14:36:27.2476789Z     status: 404,
2024-01-31T14:36:27.2476970Z     statusText: 'Not Found',
2024-01-31T14:36:27.2477082Z     headers: {
2024-01-31T14:36:27.2477253Z       server: 'nginx',
2024-01-31T14:36:27.2477467Z       date: 'Wed, 31 Jan 2024 14:36:27 GMT',
2024-01-31T14:36:27.2477833Z       'content-type': 'application/vnd.api+json; charset=utf-8',
2024-01-31T14:36:27.2478140Z       'transfer-encoding': 'chunked',
2024-01-31T14:36:27.2478390Z       connection: 'close',
2024-01-31T14:36:27.2478669Z       'x-frame-options': 'SAMEORIGIN',
2024-01-31T14:36:27.2478966Z       'x-xss-protection': '1; mode=block',
2024-01-31T14:36:27.2479296Z       'x-content-type-options': 'nosniff',
2024-01-31T14:36:27.2479597Z       'x-download-options': 'noopen',
2024-01-31T14:36:27.2479814Z       'x-permitted-cross-domain-policies': 'none',
2024-01-31T14:36:27.2480070Z       'referrer-policy': 'strict-origin-when-cross-origin',
2024-01-31T14:36:27.2480275Z       'cache-control': 'no-cache',
2024-01-31T14:36:27.2480537Z       'x-request-id': '885ed85b-c08d-40eb-871b-d51c504a6b08',
2024-01-31T14:36:27.2480740Z       'x-runtime': '0.043932',
2024-01-31T14:36:27.2480900Z       vary: 'Origin'
2024-01-31T14:36:27.2481015Z     },
2024-01-31T14:36:27.2481109Z     config: {
2024-01-31T14:36:27.2481231Z       transitional: [Object],
2024-01-31T14:36:27.2481358Z       adapter: [Function: httpAdapter],
2024-01-31T14:36:27.2481488Z       transformRequest: [Array],
2024-01-31T14:36:27.2481628Z       transformResponse: [Array],
2024-01-31T14:36:27.2481744Z       timeout: 30000,
2024-01-31T14:36:27.2481937Z       xsrfCookieName: 'XSRF-TOKEN',
2024-01-31T14:36:27.2482130Z       xsrfHeaderName: 'X-XSRF-TOKEN',
2024-01-31T14:36:27.2482256Z       maxContentLength: -1,
2024-01-31T14:36:27.2482386Z       maxBodyLength: -1,
2024-01-31T14:36:27.2482517Z       validateStatus: [Function: validateStatus],
2024-01-31T14:36:27.2482725Z       headers: [Object],
2024-01-31T14:36:27.2482917Z       baseURL: 'https://app.testomat.io',
2024-01-31T14:36:27.2483242Z       method: 'put',
2024-01-31T14:36:27.2483479Z       url: '/api/reporter/9e03b9c0',
2024-01-31T14:36:27.2483711Z       data: '{"api_key":"6y84ad5143zj","status_event":"fail"}'
2024-01-31T14:36:27.2483995Z     },
2024-01-31T14:36:27.2484107Z     request: <ref *1> ClientRequest {
2024-01-31T14:36:27.2484732Z       _events: [Object: null prototype],
2024-01-31T14:36:27.2485076Z       _eventsCount: 7,
2024-01-31T14:36:27.2485196Z       _maxListeners: undefined,
2024-01-31T14:36:27.2485338Z       outputData: [],
2024-01-31T14:36:27.2485446Z       outputSize: 0,
2024-01-31T14:36:27.2486205Z       writable: true,
2024-01-31T14:36:27.2486319Z       destroyed: false,
2024-01-31T14:36:27.2486476Z       _last: true,
2024-01-31T14:36:27.2486590Z       chunkedEncoding: false,
2024-01-31T14:36:27.2486712Z       shouldKeepAlive: false,
2024-01-31T14:36:27.2486899Z       maxRequestsOnConnectionReached: false,
2024-01-31T14:36:27.2487034Z       _defaultKeepAlive: true,
2024-01-31T14:36:27.2487173Z       useChunkedEncodingByDefault: true,
2024-01-31T14:36:27.2487354Z       sendDate: false,
2024-01-31T14:36:27.2487472Z       _removedConnection: false,
2024-01-31T14:36:27.2487643Z       _removedContLen: false,
2024-01-31T14:36:27.2487766Z       _removedTE: false,
2024-01-31T14:36:27.2487887Z       strictContentLength: false,
2024-01-31T14:36:27.2488071Z       _contentLength: 48,
2024-01-31T14:36:27.2488287Z       _hasBody: true,
2024-01-31T14:36:27.2488449Z       _trailer: '',
2024-01-31T14:36:27.2488556Z       finished: true,
2024-01-31T14:36:27.2488666Z       _headerSent: true,
2024-01-31T14:36:27.2488826Z       _closed: false,
2024-01-31T14:36:27.2488937Z       socket: [TLSSocket],
2024-01-31T14:36:27.2489303Z       _header: 'PUT /api/reporter/9e03b9c0 HTTP/1.1\r\n' +
2024-01-31T14:36:27.2489538Z         'Accept: application/json, text/plain, */*\r\n' +
2024-01-31T14:36:27.2489752Z         'Content-Type: application/json\r\n' +
2024-01-31T14:36:27.2490004Z         'User-Agent: axios/0.25.0\r\n' +
2024-01-31T14:36:27.2490195Z         'Content-Length: 48\r\n' +
2024-01-31T14:36:27.2490432Z         'Host: app.testomat.io\r\n' +
2024-01-31T14:36:27.2490613Z         'Connection: close\r\n' +
2024-01-31T14:36:27.2490766Z         '\r\n',
2024-01-31T14:36:27.2490926Z       _keepAliveTimeout: 0,
2024-01-31T14:36:27.2491053Z       _onPendingData: [Function: nop],
2024-01-31T14:36:27.2491239Z       agent: [Agent],
2024-01-31T14:36:27.2491355Z       socketPath: undefined,
2024-01-31T14:36:27.2491515Z       method: 'PUT',
2024-01-31T14:36:27.2491679Z       maxHeaderSize: undefined,
2024-01-31T14:36:27.2491808Z       insecureHTTPParser: undefined,
2024-01-31T14:36:27.2491992Z       joinDuplicateHeaders: undefined,
2024-01-31T14:36:27.2492189Z       path: '/api/reporter/9e03b9c0',
2024-01-31T14:36:27.2492307Z       _ended: true,
2024-01-31T14:36:27.2492487Z       res: [IncomingMessage],
2024-01-31T14:36:27.2492601Z       aborted: false,
2024-01-31T14:36:27.2492791Z       timeoutCb: null,
2024-01-31T14:36:27.2492913Z       upgradeOrConnect: false,
2024-01-31T14:36:27.2493026Z       parser: null,
2024-01-31T14:36:27.2493188Z       maxHeadersCount: null,
2024-01-31T14:36:27.2493307Z       reusedSocket: false,
2024-01-31T14:36:27.2493591Z       host: 'app.testomat.io',
2024-01-31T14:36:27.2493781Z       protocol: 'https:',
2024-01-31T14:36:27.2493904Z       _redirectable: [Writable],
2024-01-31T14:36:27.2494078Z       [Symbol(kCapture)]: false,
2024-01-31T14:36:27.2494202Z       [Symbol(kBytesWritten)]: 0,
2024-01-31T14:36:27.2494412Z       [Symbol(kNeedDrain)]: false,
2024-01-31T14:36:27.2494535Z       [Symbol(corked)]: 0,
2024-01-31T14:36:27.2494670Z       [Symbol(kOutHeaders)]: [Object: null prototype],
2024-01-31T14:36:27.2494857Z       [Symbol(errored)]: null,
2024-01-31T14:36:27.2494982Z       [Symbol(kUniqueHeaders)]: null
2024-01-31T14:36:27.2495159Z     },
2024-01-31T14:36:27.2495353Z     data: { message: 'Run 9e03b9c0 not found' }
2024-01-31T14:36:27.2495470Z   },
2024-01-31T14:36:27.2495815Z   isAxiosError: true,
2024-01-31T14:36:27.2495932Z   toJSON: [Function: toJSON]
2024-01-31T14:36:27.2496134Z }

##[error]Bash exited with code '1'.

**Expected behavior**
Tests are completed and uploaded to Testomatio

**Screenshots**
If applicable, add screenshots or video to help explain your problem.

**Desktop (please complete the following information):**
 - OS: Ubuntu 22
 - Browser chrome
 - Browser VersionN/A
 - Application: production

**Additional context**

**Comment by TetianaKhomenko** [comment]
Hi @leagaleano-codere! Forwarding reply from Slack:

_When you pass TESTOMATIO_RUN this means that Run with that ID is already created.
TESTOMATIO_RUN expects ID of already created run.
Run was not created or ID was passed in a wrong format._

Does this help?

**Comment by TetianaKhomenko** [comment]
Hi @leagaleano-codere! We are closing this ticket for now. Please feel free to re-open it if the issue persists.
